# Generated by Django 3.0.4 on 2020-03-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='average_score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
