# Generated by Django 3.0.4 on 2020-03-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200326_0728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='moviedb',
        ),
    ]
