# Generated by Django 3.0.4 on 2020-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200401_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('starring', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=2000)),
                ('genre', models.CharField(max_length=20)),
                ('average_score', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('release_date', models.DateField(null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'db_table': 'movie_test',
            },
        ),
    ]
