from movie.models import Movie
from django.utils import timezone

m = Movie(title="Parasite", starring="song, park", summary="king god", genre="drama", average_score="6.63", release_date="2020-04-06", pub_date=timezone.now())
m.save()
m = Movie(title="Sonic", starring="kim, yoon", summary="suck", genre="drama", average_score="2.37", release_date="2020-05-11", pub_date=timezone.now())
m.save()
m = Movie(title="GOD", starring="son", summary="fool", genre="drama", average_score="4.33", release_date="2020-03-29", pub_date=timezone.now())
m.save()
m = Movie(title="Urf", starring="park", summary="omg", genre="action", average_score="5.63", release_date="2020-06-06", pub_date=timezone.now())
m.save()
m = Movie(title="lit", starring="tana", summary="asas", genre="action", average_score="5.93", release_date="2020-03-06", pub_date=timezone.now())
m.save()
m = Movie(title="rat", starring="dana", summary="qtqtsfs", genre="action", average_score="1.63", release_date="2020-03-11", pub_date=timezone.now())
m.save()
m = Movie(title="covid19", starring="tqtq", summary="FSAGVDSBDDSGS", genre="comedy", average_score="9.63", release_date="2020-1-06", pub_date=timezone.now())
m.save()
m = Movie(title="sweb", starring="rtrt", summary="gsgeafewrwqrqwr", genre="comedy", average_score="8.23", release_date="2020-02-06", pub_date=timezone.now())
m.save()
m = Movie(title="fword", starring="god", summary="gsgeagewagaw", genre="comedy", average_score="2.63", release_date="2020-02-15", pub_date=timezone.now())
m.save()
m = Movie(title="asdfsd", starring="king", summary="rereshreshrere", genre="comedy", average_score="5.63", release_date="2020-03-06", pub_date=timezone.now())
m.save()
m = Movie(title="tetris", starring="nertd", summary="gewgwatweewtwa", genre="comedy", average_score="5.63", release_date="2020-03-06", pub_date=timezone.now())
m.save()
